---
title: ""
format: html
---
## Difficulty of each type of hole versus score
<br>
```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE
library(tidyverse)
library(patchwork)
library(dplyr)
library(ggpubr)
golf_data <- read_csv(file = "dg_new_course_table.csv")
```

```{r}
#| echo: FALSE
#| message: FALSE
p1 <- golf_data |> ggplot(mapping = aes(x = adj_par_3_score, y = adj_score_to_par)) +
    geom_point() + 
    geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between Par 3 Score and Total Score", subtitle = "Clear Relation", x = "Par 3 Score", y = "Total Score") + theme(plot.title = element_text(face = "bold"))  

model <- lm(adj_score_to_par ~ adj_par_3_score, data = golf_data)
slope <- coef(model)[2]

p2 <- golf_data |> ggplot(mapping = aes(x = adj_par_4_score, y = adj_score_to_par)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between Par 4 Score and Total Score", subtitle = "Clear Relation", x = "Par 4 Score", y = "Total Score") + theme(plot.title = element_text(face = "bold")) 

model2 <- lm(adj_score_to_par ~ adj_par_4_score, data = golf_data)
slope2 <- coef(model2)[2]

p3 <- golf_data |> ggplot(mapping = aes(x = adj_par_5_score, y = adj_score_to_par)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between Par 5 Score and Total Score", subtitle = "Clear Relation", x = "Par 5 Score", y = "Total Score") + theme(plot.title = element_text(face = "bold")) 


model3 <- lm(adj_score_to_par ~ adj_par_5_score, data = golf_data)
slope3 <- coef(model3)[2]

combined_plot <- ggplot() + 
  geom_point(data = golf_data, aes(x = adj_par_3_score, y = adj_score_to_par, color = "Par 3"), alpha = 0.35) + 
  geom_smooth(data = golf_data, aes(x = adj_par_3_score, y = adj_score_to_par, color = "Par 3"), method = "lm", se = FALSE) +
  geom_point(data = golf_data, aes(x = adj_par_4_score, y = adj_score_to_par, color = "Par 4"), alpha = 0.35) + 
  geom_smooth(data = golf_data, aes(x = adj_par_4_score, y = adj_score_to_par, color = "Par 4"), method = "lm", se = FALSE) + 
  geom_point(data = golf_data, aes(x = adj_par_5_score, y = adj_score_to_par, color = "Par 5"), alpha = 0.35) + 
  geom_smooth(data = golf_data, aes(x = adj_par_5_score, y = adj_score_to_par, color = "Par 5"), method = "lm", se = FALSE) + 
  labs(title = "Relation between diffficulty of different holes and score", x = "Hole Difficulty", y = "Score", color = "Strokes Gained") + 
  theme(plot.title = element_text(face = "bold")) +
  scale_color_manual(values = c("Par 3" = "blue", "Par 4" = "red", "Par 5" = "green"))

p1
p2
p3
combined_plot
```

