---
title: "temp"
---

golf_data |> ggplot(mapping = aes(x = ott_sg, y = adj_score_to_par)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE)   + labs(title = "Relation between shots off the tee (drives) and score", x= "Strokes gained off the tee (Driving)", y = "Score") + theme(plot.title = element_text(face = "bold")) 
golf_data |> ggplot(mapping = aes(x = app_sg, y = adj_score_to_par)) + 
   geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between approach shots and score", x = "Strokes gained on the approach shot", y = "Score") +     
  theme(plot.title = element_text(face = "bold"))
golf_data |> ggplot(mapping = aes(x = arg_sg, y = adj_score_to_par)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between shots around the green and score", x = "Strokes gained around the green (short game)", y = "Score") + theme(plot.title = element_text(face = "bold")) 
golf_data |> ggplot(mapping = aes(x = putt_sg, y = adj_score_to_par)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(title = "Relation between putting and score", x = "Strokes Gained Putting", y = "Score") + theme(plot.title = element_text(face = "bold")) 